### ISSUE TITLE
Or gate visualisation

### ISSUE THREAD

**Issue by petarpetarpetar** [petarpetarpetar/simulator#1]
trying to draw a or gate using ellipse(), ard() and rect() processing functions. So far I managed to draw And and Not gate and they look something like this:

  rect(x-20,y-10,10,5);//inA
  rect(x-20,y+5,10,5);//inB
  rect(x+17,y-2,10,5);
  rect(x-10,y-15,10,30);
  arc(x, y, 35, 30, -HALF_PI, HALF_PI); 

  y+=30;
  rect(x-10,y-2,10,5);
  triangle(x,y-15,x,y+15,x+20,y+2);  
  rect(x+28,y-1,10,5);
  ellipse(x+23,y+2,10,10);

X and Y were the mouseX and mouseY cords.

**Comment by petarpetarpetar** [comment]
realised that Or could be made using 3 arc() functions so I will try to get it done tomorrow.

**Comment by djokjulapfe** [comment]
You could also load a .svg or create a global set of PShape objects.

**Comment by petarpetarpetar** [comment]
after some work decided to just get it done by loading a image of or gate.
